name: Aqar Phone Extractor

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          playwright install --with-deps chromium

      - name: Run phone extractor
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEET_NAME: Riyadh
        run: |
          python extract_aqar_phones.py
